import * as assert from "node:assert/strict";
import test from "node:test";
import {
    ALL_COMMENTS_NOTE_PATH,
    buildAllCommentsNoteContent,
    buildCommentLocationUrl,
    findCommentLocationTargetInMarkdownLine,
    isAllCommentsNotePath,
    LEGACY_ALL_COMMENTS_NOTE_PATH,
    parseCommentLocationUrl,
} from "../src/core/allCommentsNote";
import type { Comment } from "../src/commentManager";

function createComment(overrides: Partial<Comment> = {}): Comment {
    return {
        id: "comment-1",
        filePath: "Folder/Note.md",
        startLine: 4,
        startChar: 2,
        endLine: 4,
        endChar: 7,
        selectedText: "hello",
        selectedTextHash: "hash-1",
        comment: "This is a side note.",
        timestamp: 1710000000000,
        resolved: false,
        ...overrides,
    };
}

test("buildCommentLocationUrl encodes vault, file, and comment id", () => {
    const url = buildCommentLocationUrl("dev vault", createComment({
        filePath: "Folder/My Note.md",
        id: "comment 1",
    }));

    assert.equal(
        url,
        "obsidian://side-note2-comment?vault=dev%20vault&file=Folder%2FMy%20Note.md&commentId=comment%201"
    );
});

test("parseCommentLocationUrl extracts file path and comment id", () => {
    assert.deepEqual(
        parseCommentLocationUrl("obsidian://side-note2-comment?vault=dev&file=Folder%2FMy%20Note.md&commentId=comment%201"),
        {
            filePath: "Folder/My Note.md",
            commentId: "comment 1",
        },
    );
    assert.equal(parseCommentLocationUrl("obsidian://open?vault=dev&file=Folder%2FMy%20Note.md"), null);
});

test("findCommentLocationTargetInMarkdownLine finds the side note target in a generated list row", () => {
    assert.deepEqual(
        findCommentLocationTargetInMarkdownLine("- [hello](obsidian://side-note2-comment?vault=dev&file=Folder%2FNote.md&commentId=comment-1)  #hi"),
        {
            filePath: "Folder/Note.md",
            commentId: "comment-1",
        },
    );
    assert.equal(findCommentLocationTargetInMarkdownLine("**Folder/Note.md**"), null);
});

test("buildAllCommentsNoteContent groups comments by file and shows selected text and comment", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            filePath: "B.md",
            selectedText: "beta",
            comment: "Comment B",
            startLine: 8,
        }),
        createComment({
            id: "comment-2",
            filePath: "A.md",
            selectedText: "alpha",
            comment: "Comment A",
            startLine: 2,
            resolved: true,
        }),
    ]);

    assert.doesNotMatch(content, /# Side comments/);
    assert.doesNotMatch(content, /Generated by SideNote2/);
    assert.doesNotMatch(content, /Total comments:/);
    assert.match(content, /\*\*A\.md\*\*/);
    assert.match(content, /\*\*B\.md\*\*/);
    assert.match(content, /-\s+\[~~alpha~~\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=A\.md&commentId=comment-2\)/);
    assert.doesNotMatch(content, /Comment A/);
    assert.doesNotMatch(content, /\*\*A\.md\*\*\n\n-/);
    assert.doesNotMatch(content, /comment-2\)\n\n-/);
});

test("buildAllCommentsNoteContent renders an empty file when there are no comments", () => {
    const content = buildAllCommentsNoteContent("dev", []);

    assert.equal(content, "");
});

test("buildAllCommentsNoteContent ignores comments attached to the generated aggregate note", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            filePath: ALL_COMMENTS_NOTE_PATH,
            selectedText: "self",
        }),
        createComment({
            id: "comment-2",
            filePath: "Z.md",
            selectedText: "real",
        }),
    ]);

    assert.doesNotMatch(content, /\[\[SideNote2 comments\.md\]\]/);
    assert.match(content, /\*\*Z\.md\*\*/);
});

test("buildAllCommentsNoteContent escapes markdown-heavy selections and truncates long previews", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            selectedText: "Use `/path/to/SideNote2`, `[Vault]`, and `<tag>` placeholders instead of machine-local paths in docs.",
        }),
    ]);

    assert.match(content, /\[Use \\`\/path\/to\/SideNote2\\`, \\`\\\[Vault\\\]\\`, and \\`\\<tag\\>\\` placeholders instead of mach\.\.\.\]/);
});

test("buildAllCommentsNoteContent includes extracted comment tags for search", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            comment: "Track this with #hi and #follow/up next.",
        }),
    ]);

    assert.match(content, /-\s+\[hello\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=comment-1\)  #hi #follow\/up/);
});

test("buildAllCommentsNoteContent labels page notes and orphaned notes", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            id: "page-note",
            anchorKind: "page",
            selectedText: "Note",
            startLine: 0,
            startChar: 0,
            endLine: 0,
            endChar: 0,
        }),
        createComment({
            id: "orphan-note",
            orphaned: true,
            selectedText: "missing text",
            startLine: 10,
        }),
    ]);

    assert.match(content, /\[page note · Note\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=page-note\)/);
    assert.match(content, /\[orphaned · missing text\]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=orphan-note\)/);
});

test("buildAllCommentsNoteContent expands mentioned pages and collapses duplicates per comment", () => {
    const content = buildAllCommentsNoteContent("dev", [
        createComment({
            id: "page-note",
            anchorKind: "page",
            selectedText: "Folder/Note",
            comment: "See [[Another page]] and [[Another page|Alias]] plus [[Third page]].",
            startLine: 0,
            startChar: 0,
            endLine: 0,
            endChar: 0,
        }),
        createComment({
            id: "anchored-note",
            selectedText: "hello",
            comment: "Track [[Roadmap]] for this",
            startLine: 4,
        }),
    ], {
        getMentionedPageLabels: (comment) => {
            if (comment.id === "page-note") {
                return ["Another page", "Another page", "Third page"];
            }

            if (comment.id === "anchored-note") {
                return ["Roadmap"];
            }

            return [];
        },
    });

    assert.match(content, /- \[page note · Another page]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=page-note\)/);
    assert.match(content, /- \[page note · Third page]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=page-note\)/);
    assert.match(content, /- \[hello · Roadmap]\(obsidian:\/\/side-note2-comment\?vault=dev&file=Folder%2FNote\.md&commentId=anchored-note\)/);
    assert.equal(content.match(/page note · Another page/g)?.length ?? 0, 1);
});

test("isAllCommentsNotePath matches the generated note path", () => {
    assert.equal(isAllCommentsNotePath(ALL_COMMENTS_NOTE_PATH), true);
    assert.equal(isAllCommentsNotePath(LEGACY_ALL_COMMENTS_NOTE_PATH), true);
    assert.equal(isAllCommentsNotePath("Random.md"), false);
});
